### ISSUE TITLE
sfdxBuildPipeline - steps not executed in case of failure

### ISSUE THREAD

**Issue by fischerp** [claimvantage/sfdx-jenkins-shared-library#103]
### Summary

If the build fails by any reason in of its parallel execution, the following steps are never executed.
- stage("publish")
- stage("slack notification end") [optional]
- stage("clean")
- stage("final stage") [optional]

### Steps To Reproduce:

1.  Try to install an invalid package
2. Confirm that none of the steps provided above were executed 

### Expected result

I'm not sure whether the publish stage should be executed or not, but the last three should be. That's for sure.

### Actual result

The build just stops in case of failure.

### Additional information

![image](https://user-images.githubusercontent.com/8863913/107660397-1f334700-6c80-11eb-9a0e-f63e466a805c.png)

**Comment by jefersonchaves** [comment]
That is great, thanks for that, we just need to think if we are introducing the right responsibility and what steps should happen after failure or regardless of failure.

**Comment by fischerp** [comment]
Fixed
![image](https://user-images.githubusercontent.com/8863913/108208984-a588d680-7121-11eb-8b94-08edd68b115c.png)

**Comment by fischerp** [comment]
![image](https://user-images.githubusercontent.com/8863913/108209171-e41e9100-7121-11eb-9373-cc1a2dad68e0.png)

**Comment by fischerp** [comment]
Reopening this issue as we started getting the following error:
`hudson.remoting.ProxyException: org.codehaus.groovy.runtime.typehandling.GroovyCastException: Cannot cast object '{default=null}' with class 'java.util.HashMap' to class 'org.jenkinsci.plugins.pipeline.modeldefinition.model.Root' due to: groovy.lang.GroovyRuntimeException: Could not find matching constructor for: org.jenkinsci.plugins.pipeline.modeldefinition.model.Root(java.util.HashMap)`
