### ISSUE TITLE
sfdxBuildPipeline - build result incorrect status

### ISSUE THREAD

**Issue by fischerp** [claimvantage/sfdx-jenkins-shared-library#109]
### Summary

When running X builds in parallel, it shows success even when one of the paths fail. It should fail.

### Steps To Reproduce:

1.  Run builds in parallel.
1.  One of them should fail (Probably forcing an error would be easier way to test)

### Expected result

The build status should fail

### Actual result

The build status is success

**Comment by jefersonchaves** [comment]
This seems to be related to #103
