### ISSUE TITLE
runApexTests progress messages are inconsistent with test results

### ISSUE THREAD

**Issue by KeithClarke** [claimvantage/sfdx-jenkins-shared-library#54]
Progress messages of this nature are generated:
```
Test run status is "Processing" with 614 of 3034 methods run (1 methods failed) after 1 sleeps of 1 minutes each
...
Test run status is "Processing" with 2442 of 3034 methods run (1 methods failed) after 9 sleeps of 1 minutes each
Test run status is "Completed" with 2638 of 3034 methods run (1 methods failed) after 10 sleeps of 1 minutes each
```
where the final message (and probably earlier messages) undercount the number of completed tests.

Looks like this problem (perhaps only with parallel tests): https://salesforce.stackexchange.com/questions/229177/apextestrunresults-status-is-set-to-complete-and-all-tests-pass-but-the-enqueu. That suggests adding a final query of `ApexTestResult` might produce more correct results but not important here as the JSON tests results are what really matters.

**Comment by jefersonchaves** [comment]
Based on the thread this seems to be a platform issue and not a library issue.
