### ISSUE TITLE
Make Apex test timeout configurable

### ISSUE THREAD

**Issue by KeithClarke** [claimvantage/sfdx-jenkins-shared-library#55]
I'd like to see a timeout value that can be set on `sfdxBuildPipeline` and passed through to `runApexTests` as the current 4-hour default is too big and some builds get stuck and hit that timeout:

![4hours](https://user-images.githubusercontent.com/2153816/57866003-7cbe0980-77f6-11e9-858f-ab752f57f1cb.png)

Too big particularly for small projects or projects that run tests in parallel. In the project illustrated in the image, I would set the timeout to say 80 minutes.

**Comment by jefersonchaves** [comment]
Hey @KeithClarke: I liked the idea as well. Maybe that is something good for someone to start (then we can stick "good first issue").

**Comment by KeithClarke** [comment]
Agreed @jefersonchaves. We have a new guy called Ivan starting next week. Could you coach him through this?

**Comment by jefersonchaves** [comment]
Sure, do you have something in mind about your desired syntax for sfdxBuildPipeline?

**Comment by KeithClarke** [comment]
Maybe `apexTestsTimoutMinutes` property on sfdxBuildPipeline and `timoutMinutes` property on runApexTests; pretty ugly though.

**Comment by jefersonchaves** [comment]
Hey @IvanPinto: would you like to look into this?

**Comment by IvanPinto** [comment]
Hey @jefersonchaves! Sure, I'll need some coaching through the process but I would definitely like to learn and start working on the sfdx pipelines.

**Comment by jefersonchaves** [comment]
Sure, ping me with any question or concern.

**Comment by JAertgeerts** [comment]
@IvanPinto Have you worked on this at all? If not, I'll submit a PR.

**Comment by IvanPinto** [comment]
Hi @JAertgeerts! I made no further changes, please feel free to submit PR.
