### ISSUE TITLE
Allow keepOrgs to be set in Jenkins

### ISSUE THREAD

**Issue by KeithClarke** [claimvantage/sfdx-jenkins-shared-library#56]
When diagnosing unexpected build problems, being able to examine the scratch org after the build has completed is a frequent need. Having to edit the Jenkinsfile to do that is inconvenient; would be nice to be able to set something in the Jenkins configuration instead.

**Comment by jefersonchaves** [comment]
Hi @KeithClarke: do you mean having an instance-level config?

🗒 When I have to change builds I tend to use Jenkins Replay and change the script.

**Comment by fischerp** [comment]
I think the replay option is the best way to address that too. So we have free access to change the jenkinsfile without touching the code repository.

**Comment by jefersonchaves** [comment]
This seems that was addressed but feel free to reopen.
