### ISSUE TITLE
Return extended status for Apex test failures

### ISSUE THREAD

**Issue by KeithClarke** [claimvantage/sfdx-jenkins-shared-library#57]
See https://salesforce.stackexchange.com/questions/262893/any-way-to-get-consistent-test-counts-when-parallel-testing-is-used.

After the test run add:

`sfdx force:data:soql:query --resultformat human --usetoolingapi --query "select ApexClass.Name, Status, ExtendedStatus from ApexTestQueueItem  where ParentJobId = '707L000001T8VPC'"`

and output the results in the log to get some visibility of the cause. Output is e.g.:

```
APEXCLASS.NAME                      STATUS     EXTENDEDSTATUS
──────────────────────────────────  ─────────  ──────────────
PaymentCalculatorForDisabilityTest  Completed  (46/46)
```

**Comment by jefersonchaves** [comment]
@KeithClarke: I'm closing this because it seems that you already implemented this feature and the inconsistency, if still any, lives on sfdx tooling - then might be worth posting an issue to [cli repo](https://github.com/forcedotcom/cli).
