### ISSUE TITLE
runLightningTests should support lwc jest testing

### ISSUE THREAD

**Issue by JAertgeerts** [claimvantage/sfdx-jenkins-shared-library#64]
**Is your feature request related to a problem? Please describe.**
The runLightningTests function currently supports aura lightning:test:run. For those developing lwc, there should be the ability to run unit tests using jest.

**Describe the solution you'd like**
ability to define that the project is using lwc, would run npm run test:unit. Function would scan for a package.json to ensure dependencies are defined and installed.

**Additional context**
https://developer.salesforce.com/docs/component-library/documentation/lwc/lwc.testing

**Comment by jefersonchaves** [comment]
Hi @JAertgeerts: great idea, but do you think is better to incorporate on runLightningTests or create a separate one for LWC? Asking because `sfdx force:lightning:test:run` is unable to run Jest tests, so unsure about the right encapsulation (the code might also get tangled), perhaps worth considering a separate command.

**Comment by JAertgeerts** [comment]
Agreed. Separate function so you can define your pipeline with either using one or both.

**Comment by KeithClarke** [comment]
We need this internally in ClaimVantage too. Just scripting to parse e.g.:
```
PASS force-app/main/default/lwc/navigationService/__tests__/navigationService.base.test.js
PASS force-app/main/default/lwc/progressIndicator/__tests__/progressIndicator.base.test.js
FAIL force-app/main/default/lwc/claimDetailsAdoption/__tests__/claimDetailsAdoption.test.js
  ● claimDetailsAdoption tests › should trigger 'childcomponentregister' event when it's loaded

    expect(jest.fn()).toHaveBeenCalled()

    Expected number of calls: >= 1
    Received number of calls:    0

      12 |         document.body.appendChild(element);
      13 | 
    > 14 |         expect(handler).toHaveBeenCalled();
         |         ^
      15 |         expect(handler.mock.calls[0][0].detail.callbacks.validate).not.toBeUndefined();
      16 |         expect(handler.mock.calls[0][0].detail.callbacks.validate).not.toBeNull();
      17 |         expect(typeof(handler.mock.calls[0][0].detail.callbacks.validate)).toBe('function');

      at Object.it (force-app/main/default/lwc/claimDetailsAdoption/__tests__/claimDetailsAdoption.test.js:14:9)

FAIL force-app/main/default/lwc/claimReason/__tests__/claimReason.test.js
```

**Comment by KeithClarke** [comment]
This works:
```
    afterTestStage: {  org ->

        echo "${org.name} running LWC tests"

        // Install LWC test runner and TAP reporter; config is in package.json and perhaps dependency should be too
        shWithStatus "npm install @salesforce/sfdx-lwc-jest --save-dev"
        shWithStatus "npm install --dev jest-tap-reporter"

        // Test result folder
        sh "mkdir -p ${env.WORKSPACE}/tests/${env.BUILD_NUMBER}/${org.name}"

        // Run tests - deliberately no status check so build doesn't fail immediately
        sh returnStatus: true, script: "npm run test:unit > ${env.WORKSPACE}/tests/${env.BUILD_NUMBER}/${org.name}/test-result-lwc-junit.txt"
    }
```
so with some cleanup could be added to this library. Not too clear on the right pattern to have the libraries setup.

**Comment by jefersonchaves** [comment]
Hi @KeithClarke : fair enough but don't you think would be better to have this in a separate command? Something like `runLwcTests` that could potentially install the dependencies on package.json (that should be sfdx-lwc-jest and the tap reporter).

**Comment by KeithClarke** [comment]
Hi @jefersonchaves +1 to an extra command. FYI, I'm trying to get this one https://www.npmjs.com/package/jest-junit to work instead of the TAP output.

**Comment by jefersonchaves** [comment]
Cool, yesterday Feb 20th, Salesforce [introduced](https://developer.salesforce.com/media/salesforce-cli/releasenotes.html) a set of features that probably would make this easier:
* `force:lightning:lwc:test:run`
* `force:lightning:lwc:test:setup`.

Probably worth trying on current build before introducing in the library.
